---
# file: roles/corosync/tasks/configuration.yml
- name: Configuring Corosync
  template:
    src=etc/corosync/corosync.conf.j2
    dest=/etc/corosync/corosync.conf
  notify: restart corosync

- name: Making sure that Corosync service is started
  ansible.builtin.systemd:
    name: corosync
    state: started
    enabled: yes

- meta: flush_handlers
